"""
Author(s): Matyáš Sedmidubský <sedmidubsky@cesnet.cz>

Copyright: (C) 2026 CESNET, z.s.p.o.

Module implements Legacy Stateful TRex generator class.

Legacy stateful (STF) mode is the original TRex mode.
In contrast with Stateless and Advanced Stateful modes, it does not
provide any interactive API. TRex is started via its daemon with a
traffic profile file and all port attributes (VLAN, MAC addresses)
must be set in the TRex configuration file before TRex is started.
"""

import os
import pathlib
import shutil
import tempfile
import time
from typing import Any

import lbr_trex_client  # noqa: F401
import yaml

from lbr_testsuite.trex.trex_base import TRexBase


class TRexLegacyStateful(TRexBase):
    """Legacy Stateful TRex generator class.

    In contrast with Stateless and Advanced Stateful modes, there
    is no interactive API for legacy stateful mode. Traffic is
    generated by starting a TRex run with a traffic profile file:

        .start(f=<profile>, d=<duration>)

    You can upload your traffic profile and its pcaps with
    ``.get_daemon().push_files(<file>)`` where <file> can be a
    list of file paths or just one file path. To get the remote
    paths you can use ``.get_daemon().get_trex_files_path()``
    and append the file names.

    Attributes
    ----------
    cfg : Any
        Parsed content of TRex configuration file. Port attributes
        (VLAN, MAC addresses) are modified here before being
        uploaded to the TRex machine.
    _remote_cfg_path : pathlib.Path
        Path to TRex configuration file (on remote TRex machine).
    _cfg_synced : bool
        True if configuration on the remote machine is in sync
        with ``cfg``. Set to False whenever ``cfg`` is modified.
        It is not set when modifying ``cfg`` directly and you should
        ``.upload_cfg()`` manually.
    """

    cfg: Any = None
    _remote_cfg_path = None
    _cfg_synced = True

    def start(self, f, d, **trex_cmd_options):
        """Start TRex run in stateful mode.

        TRex configuration file is always provided so that
        changes of port attributes (VLAN, MAC) are applied.
        Without it, TRex would use the default configuration
        file (/etc/trex_cfg.yaml) instead.

        Parameters
        ----------
        f : str
            Path (on remote TRex machine) to traffic profile
            configuration file (.yaml).
        d : int
            Duration of the run in seconds.
            Must be >= 30s.
        **trex_cmd_options : dict
            Additional TRex command line options.
        """

        if not self._cfg_synced:
            self.upload_cfg()

        trex_cmd_options.setdefault("cfg", str(self._remote_cfg_path))
        return self._daemon.start_trex(f, d, **trex_cmd_options)

    def stop(self):
        """Stop generating traffic."""

        self._daemon.stop_trex()

    def wait_on_traffic(self, timeout=None):
        """Wait until traffic generation finishes.

        Unlike in other TRex modes, there is no blocking
        ``wait_on_traffic`` call in the daemon API, so traffic
        is polled once per second.

        Parameters
        ----------
        timeout : int, optional
            Timeout in seconds. Default value means no timeout.
            Traffic is not stopped on timeout.
        """

        start = time.time()
        while self._daemon.is_running() and (timeout is None or time.time() - start < timeout):
            time.sleep(1)

    def get_stats(self):
        """Get statistics from the latest available run dump.

        Statistics can be sampled via the handler while the run
        is active. For details see official documentation.
        (https://trex-tgn.cisco.com/trex/doc/cp_docs/api/client_code.html)

        Format **doesn't** match ASTF/STL stats.

        Returns
        -------
        dict
            Latest statistics dump.
        """

        return self._daemon.get_result_obj().get_latest_dump()

    def get_daemon(self):
        """Get the TRex daemon handler for this instance.

        Returns
        -------
        CTRexClient
            TRex daemon client.
        """

        return self._daemon

    def connect(self, request, generator, conf_file, force=False):
        """Connect to TRex.

        STF TRex doesn't maintain a persistent connection, so
        only bookkeeping is performed.

        Parameters
        ----------
        request : fixture
            Special pytest fixture, here used for finalizer.
        generator : TRexGenerator
            TRex generator object.
        conf_file : str
            Path to configuration file (on local machine).
        force : bool, optional
            If True, kill previous instance if it's running
            before starting TRex.

        Returns
        -------
        TRexLegacyStateful
            Connected TRex.
        """

        self._daemon = generator.get_daemon()
        self._handler = None
        self._remote_cfg_path = pathlib.Path(
            self._daemon.get_trex_files_path(), os.path.basename(conf_file)
        )

        with open(conf_file, "r") as f:
            self.cfg = yaml.safe_load(f)

        self._ports = [i for i, ifcs in enumerate(self.cfg[0]["interfaces"]) if ifcs != "dummy"]

        if force:
            self._daemon.force_kill(confirm=False)

        request.addfinalizer(self.terminate)

        return self

    def terminate(self):
        """Terminate TRex.

        Stop any leftover traffic.
        """

        self._daemon.stop_trex()

    def set_vlan(self, vlan, port=None, upload=False):
        """Set VLAN.

        Reimplementation of parent method. As legacy stateful
        mode provides no interactive API, VLAN is set by
        modifying the TRex configuration file instead of
        talking to a running TRex.

        Parameters
        ----------
        vlan : int
            VLAN ID.
        port : int, optional
            Port ID.
            If not set, apply to all available ports.
        upload : bool, optional
            If True, upload modified configuration to the
            TRex machine right away. Otherwise, configuration
            is uploaded on next ``start`` call.
        """

        if port is None:
            ports = self._ports
        else:
            self._check_valid_port(port)
            ports = [port]

        for port_number in ports:
            self._set_port_info(port_number, vlan=vlan)

        if upload:
            self.upload_cfg()

    def get_vlan(self, port=None):
        """Get currently configured VLAN.

        Reimplementation of parent method. VLAN is read from
        the local copy of the configuration file, as there is
        no interactive API to query a running TRex.

        Parameters
        ----------
        port : int, optional
            Port ID.
            If not set, use first available port.

        Returns
        -------
        int
            VLAN ID.
        """

        if port is None:
            port = self._ports[0]

        self._check_valid_port(port)

        return self._get_port_info(port, "vlan")

    def set_dst_mac(self, mac, port=None, upload=False):
        """Set destination MAC address.

        Reimplementation of parent method. As legacy stateful
        mode provides no interactive API, MAC address is set by
        modifying the TRex configuration file instead of
        talking to a running TRex.

        Parameters
        ----------
        mac : str
            MAC address.
        port : int, optional
            Port ID.
            If not set, apply to all available ports.
        upload : bool, optional
            If True, upload modified configuration to the
            TRex machine right away. Otherwise, configuration
            is uploaded on next ``start`` call.
        """

        if port is None:
            ports = self._ports
        else:
            self._check_valid_port(port)
            ports = [port]

        for port_number in ports:
            self._set_port_info(port_number, dest_mac=mac)

        if upload:
            self.upload_cfg()

    def get_dst_mac(self, port=None):
        """Get destination MAC address.

        Reimplementation of parent method. MAC address is read
        from the local copy of the configuration file, as there
        is no interactive API to query a running TRex.

        Parameters
        ----------
        port : int, optional
            Port ID.
            If not set, use first available port.

        Returns
        -------
        str
            MAC address.
        """

        if port is None:
            port = self._ports[0]

        self._check_valid_port(port)

        return self._get_port_info(port, "dest_mac")

    def get_src_mac(self, port=None):
        """Get source MAC address.

        Reimplementation of parent method. MAC address is read
        from the local copy of the configuration file, as there
        is no interactive API to query a running TRex.

        Parameters
        ----------
        port : int, optional
            Port ID.
            If not set, use first available port.

        Returns
        -------
        str
            MAC address.
        """

        if port is None:
            port = self._ports[0]

        self._check_valid_port(port)

        return self._get_port_info(port, "src_mac")

    def start_capture(self, limit, port=None, bpf_filter=""):
        """Start capturing traffic on given port.

        Reimplementation of parent method. PCAP capture is
        not supported in legacy stateful mode.

        Raises
        ------
        NotImplementedError
            PCAP capture is not available for STF TRex.
        """

        raise NotImplementedError("PCAP capture is not available for STF TRex")

    def stop_capture(self, capture_id, pcap_file=None):
        """Stop capture and provide captured traffic.

        Reimplementation of parent method. PCAP capture is
        not supported in legacy stateful mode.

        Raises
        ------
        NotImplementedError
            PCAP capture is not available for STF TRex.
        """

        raise NotImplementedError("PCAP capture is not available for STF TRex")

    def refresh_cfg(self):
        """Read TRex configuration file from remote machine.

        Content of the remote configuration file is stored
        into ``cfg`` and marked as synced.

        Returns
        -------
        Any
            Parsed content of TRex configuration file.
        """

        if self._remote_cfg_path is None:
            raise ValueError("config path not set")

        content = self._daemon.get_file(str(self._remote_cfg_path))
        if isinstance(content, bytes):
            content = content.decode()

        self.cfg = yaml.safe_load(content)
        self._cfg_synced = True
        return self.cfg

    def upload_cfg(self):
        """Rewrite the YAML configuration on the remote machine.

        Configuration is dumped into a temporary file which is
        pushed to the TRex machine, overwriting the configuration
        file. Changes take effect when TRex is (re)started.
        """

        if self._remote_cfg_path is None:
            raise ValueError("config path not set")

        tmp_dir = tempfile.mkdtemp()
        try:
            tmp_file = os.path.join(tmp_dir, self._remote_cfg_path.name)
            with open(tmp_file, "w") as f:
                yaml.dump(self.cfg, f)

            self._daemon.push_files(tmp_file)
            self._cfg_synced = True
        finally:
            shutil.rmtree(tmp_dir, ignore_errors=True)

    def _set_port_info(self, port, **attributes):
        """Set attributes of a port in configuration file."""

        self._cfg_synced = False
        self.cfg[0]["port_info"][port].update(attributes)

    def _get_port_info(self, port, attribute):
        """Get an attribute of a port in configuration file."""

        return self.cfg[0]["port_info"][port].get(attribute)
