stages:
    - prepare
    - check
    - pytest
    - build
    - upload

default:
    image: $IMAGE_BUILD

include:
    - local: 'ci/prepare.gitlab-ci.yaml'
    - local: 'ci/check.gitlab-ci.yaml'
    - local: 'ci/pytest.gitlab-ci.yaml'
    - local: 'ci/build.gitlab-ci.yaml'
    - local: 'ci/upload.gitlab-ci.yaml'

variables:
    GIT_STRATEGY: clone
    IMAGE_BUILD: "$CI_PROJECT_PATH_SLUG/$CI_COMMIT_REF_SLUG/build"
    IMAGE_TESTS: "$CI_PROJECT_PATH_SLUG/$CI_COMMIT_REF_SLUG/tests"
