stages:
    - prepare
    - check
    - pytest
    - doc
    - build
    - upload

image: $CI_PROJECT_PATH_SLUG/$CI_COMMIT_REF_SLUG

docker:
    stage: prepare
    tags: [docker-shell]
    variables: { DOCKER_BUILDKIT: 1 }
    script: [docker build -t $CI_PROJECT_PATH_SLUG/$CI_COMMIT_REF_SLUG .]

docker-rebuild:
    extends: docker
    variables: { DOCKER_OPTS: --no-cache }
    when: manual

editorconfig:
    stage: check
    needs: []
    image: mstruebing/editorconfig-checker
    script: [ec]

pycodestyle:
    stage: check
    needs: [docker]
    script:
        - pytest --color=yes --flake8 -m flake8 --junitxml=pycodestyle.xml lbr_testsuite | tee pycodestyle.log
    artifacts:
        paths: [pycodestyle.*]
        reports: { junit: pycodestyle.xml }
        when: always

pytest:
    stage: pytest
    script:
        - pip install .
        - mkdir -p pytest/output
        - cd pytest && pytest --color=yes --basetemp=output --log-level=debug --junitxml=report.xml $PYTESTS_ARGS | tee report.log
    artifacts:
        paths: [pytest/output, pytest/report.*]
        reports: { junit: pytest/report.xml }
        when: always

doc:
    stage: doc
    script:
        - make -C doc html
    artifacts:
        paths: [doc/build/html]
    environment:
        name: $CI_COMMIT_REF_SLUG/$CI_BUILD_NAME
        url: $CI_JOB_URL/artifacts/file/doc/build/html/index.html

build:
    stage: build
    script:
        - python3.6 setup.py bdist_wheel
    artifacts:
        paths: [dist]

upload:
    stage: upload
    script:
        - |
            { CODE=0; TWINE_PASSWORD=${LRB_PYPI_PASSWORD} TWINE_USERNAME=${LRB_PYPI_USERNAME} python3.6 -m twine upload --verbose --repository-url ${LBR_PYPI_REPOSITORY_URL} dist/* | tee output.txt || CODE=$?; }
        - if [[ $CODE -ne 0 ]]; then
        -    ERR_MSG=`cat output.txt | tail -n -1`
        -    |
            FILE_EXISTS='{"message":"Validation failed: File name has already been taken"}'
        -    if [[ "$ERR_MSG" != "$FILE_EXISTS" ]]; then
        -        exit 1
        -    fi
        - fi
    only: ['master']

variables:
    GIT_STRATEGY: clone
