FROM python:3.11

ARG VENV_PATH=/opt/testsuite_venv


COPY pyproject.toml pdm.lock /tmp/
RUN python3.11 -m venv $VENV_PATH

ENV PATH="$VENV_PATH/bin:$PATH"

RUN python3.11 -m pip install 'pdm' && cd /tmp && pdm use -f $VENV_PATH && pdm install
