FROM python:3.11

ARG VENV_PATH=/opt/testsuite_venv


COPY Pipfile Pipfile.lock /tmp/
RUN python3.11 -m venv $VENV_PATH

ENV PATH="$VENV_PATH/bin:$PATH"
ENV VIRTUAL_ENV="$VENV_PATH"

RUN python3.11 -m pip install 'pipenv' && cd /tmp && pipenv install --dev --deploy
