# syntax=docker/dockerfile:1.3-labs

FROM oraclelinux:8

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG en_US.UTF-8

ARG VENV_PATH=/opt/testsuite_venv


COPY Pipfile Pipfile.lock /tmp/
RUN <<EOF
yum install -y oracle-epel-release-el8
yum install -y python38 python38-pip python38-devel gcc strace make
yum clean all
python3 -m venv $VENV_PATH
EOF

ENV PATH="$VENV_PATH/bin:$PATH"
ENV VIRTUAL_ENV="$VENV_PATH"

RUN python3 -m pip install 'pipenv' && cd /tmp && pipenv install --dev --deploy
