pytest:
    stage: pytest
    tags: [lbr-testsuite-ci]
    variables:
        ANSIBLE_PLAYBOOK: ansible/ci_machine.yaml
    script:
        - sudo pip install dist/lbr_testsuite*.whl
        - mkdir -p pytest_tests/output
        - cd pytest_tests && sudo pytest --color=yes --basetemp=output --log-level=debug --junitxml=report.xml $PYTESTS_ARGS | tee report.log
    artifacts:
        paths: [pytest_tests/output, pytest_tests/report.*]
        reports: { junit: pytest_tests/report.xml }
        when: always
