pytest:
    stage: pytest
    tags: [lbr-testsuite-ci]
    variables:
        ANSIBLE_PLAYBOOK: ansible/ci_machine.yaml
        RESERVE_MACHINES: lbr-testsuite-ci
    script:
        - mkdir -p pytest_tests/output
        - |
            cd pytest_tests && sudo -E pytest \
            --color=yes --basetemp=output --log-level=debug --junitxml=report.xml \
            --remote-host $CI_REMOTE_HOST -s --tb=short -k 'not topology' | tee report.log
    artifacts:
        paths: [pytest_tests/output, pytest_tests/report.*]
        reports: { junit: pytest_tests/report.xml }
        when: always
