upload:
    stage: upload
    script:
        - TWINE_PASSWORD=${LRB_PYPI_PASSWORD} TWINE_USERNAME=${LRB_PYPI_USERNAME}
            python3 -m twine upload --verbose --repository-url ${LBR_PYPI_REPOSITORY_URL} dist/*
    only: ['master']

upload to PyPI:
    stage: upload
    script:
        - TWINE_PASSWORD=${PYPI_PASSWORD} TWINE_USERNAME=${PYPI_USERNAME}
            python3 -m twine upload --verbose dist/*
    only:
        - tags
